# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo.7.0.8
    image: mongo:7.0.8
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tpwd

 
